<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Java 基础篇之异常' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Java 基础篇之异常</center></div><div class='banquan'>原文出处:本文由博客园博主SRE工程师提供。<br/>
原文连接:https://www.cnblogs.com/Tianny/p/11613995.html</div><br>
    <h2 id="异常">异常</h2>
<h3 id="异常层次">异常层次</h3>
<p><img src="./images/Java 基础篇之异常0.png" /></p>
<ul>
<li>Error：Java 运行时系统的内部错误和资源耗尽错误。应用程序不应该抛出这种类型的对象。如果出现了这样的内部错误，除了通告给用户，并尽力使程序安全地终止之外，再也无能为力了。</li>
<li>Exception
<ul>
<li>RuntimeException：由程序错误导致的异常</li>
<li>其他异常：程序本身没有问题，但由类似 IO 错误导致的异常</li>
</ul></li>
</ul>
<h3 id="checked-异常-runtime-异常">Checked 异常 &amp; Runtime 异常</h3>
<p>Checked 异常：不是 RuntimeException 类及其子类的异常实例</p>
<p>Runtime 异常：所有 RuntimeException 类及其子类的异常实例</p>
<blockquote>
<p>Java 认为 Checked 异常都是可以被处理修复的异常，所以程序必须显示处理 Checked 异常，如果程序没有处理 Checked 异常，编译时会出错。Checked 异常体现了 Java 的设计理念，没有完善错误处理的代码根本不会被执行。</p>
</blockquote>
<p>对 Checked 异常处理方式：</p>
<ul>
<li><p>当前方法明确知道如何处理该异常，应该使用 try-catch 处理该异常</p></li>
<li><p>当前方法不知道如何处理该异常，应在定义该方法时声明抛出该异常</p></li>
</ul>
<p>对 Runtime 异常的处理方式：</p>
<ul>
<li>Runtime 异常无需显式声明抛出，如果程序需要捕获 Runtime 异常，也可以使用 try-catch 块</li>
</ul>
<h3 id="throws-声明抛出异常">throws 声明抛出异常</h3>
<p>如果当前方法不知道如何处理这种类型的异常，该异常应该由上一级调用者处理，如果上一级调用者也不知道如何处理，再抛出直至交由 JVM 处理。</p>
<p>throws 声明抛出只能在方法声明中使用，可以声明抛出多个异常类。一旦使用 throws 语句声明抛出该异常，程序就无需使用 try-catch 来捕获异常了。</p>
<p>示例：下面程序声明不处理 IOException 异常，而是将该异常交由 JVM 处理</p>
<pre><code><code>import java.io.FileInputStream;
import java.io.IOException;

public class ThrowsTest {
    public void main(String[] args) throws IOException {
        FileInputStream fis = new FileInputStream(&quot;a.txt&quot;);
    }
}</code></code></pre>
<p>如果某段代码中调用了一个带 throws 声明的方法，该方法声明抛出了 Checked 异常，则表明该方法希望它的调用者来处理该异常。那么调用者在调用该方法时，要么将其放入 try 块中并显示捕获该异常，要么放在另一个带 throws 声明抛出的方法中。</p>
<p>示例代码如下：</p>
<pre><code><code>import java.io.FileInputStream;
import java.io.IOException;

public class ThrowsTest2 {

    public static void test() throws IOException {
        /* 因为 FileInputStream 的构造器声明抛出 IOException 异常
           所以调用 test() 方法 的代码要么处于 try-catch 块中
           要么处于另一个带 throws 声明抛出的方法中
        */
        FileInputStream fis = new FileInputStream(&quot;a.txt&quot;);
    }

    public static void main(String[] args) throws Exception {
        /* 因为 test() 方法声明抛出 IOException 异常
           所以调用该方法的代码要么处于 try-catch 块中
           要么处于另一个带 throws 声明抛出的方法中
        */
        test();
    }
}</code></code></pre>
<h3 id="主动抛出异常-throw">主动抛出异常 throw</h3>
<p>如果 throw 语句抛出的异常是 Checked 异常，则该 throw 语句要么处于 try 块里，显式捕获该异常，要么放在一个带 throws 声明抛出的方法中；如果 throw 语句抛出的是 Runtime 异常，则无需放在 try 块里，也无需放在带 throws 声明抛出的方法中，既可以显式的用 try-catch 来捕获并处理异常，也可以完全不理会该异常，把该异常交给该方法调用者处理。</p>
<pre><code><code>import java.io.IOException;

public class ThrowTest3 {
    public static void throwChecked(int a) throws Exception {
        if (a &gt; 0) {
            // 自行抛出 Exception 异常
            // 该代码必须处于 try 块里，或处于带 throws 声明的方法中
            throw new Exception(&quot;a的值大于0，不符合要求&quot;);
        }
    }

    public static void throwRuntime(int a) {
        if (a &gt; 0) {
            // 自行抛出 RuntimeException 异常
            // 既可以捕获该异常，也可以完全不理会该异常，把异常交给方法调用者处理
            throw new RuntimeException(&quot;a的值大于0，不符合要求&quot;);
        }
    }

    public static void main(String[] args) {
        try {
            // 调用声明抛出 Checked 异常的方法，要么显式在 try-catch 中捕获该异常，要么在 main 方法中再次声明抛出
            throwChecked(3);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        // 调用声明抛出 Runtime 异常的方法既可以显式捕获该异常，也可以不理会该异常
        throwRuntime(3);
    }
}</code></code></pre>
<h3 id="自定义异常类">自定义异常类</h3>
<pre><code><code>public class AuctionException extends Exception {
    // 无参构造器
    public AuctionException() {}
    // 带一个字符串参数的构造器
    public AuctionException(String msg) {
        super(msg);
    }
}</code></code></pre>
<h3 id="异常链">异常链</h3>
<p>将原始信息隐藏起来，仅向上提供必要的异常提示信息的处理方式，可以保证底层异常不会扩散到表现层，避免向上暴露太多的细节，符合面向对象的封装原则。</p>
<pre><code><code>public calSal() throws SalException {
    try {
        // 实现结算工资的业务逻辑
        ...
    } catch (SQLException sqle) {
        // 将原始异常记录下来，留给管理员
        ...
        // 下面异常中的 message 就是给用户的提示
        throw new SalException(&quot;访问数据库异常“);
    } catch (Exception e) {
        // 将原始异常记录下来，留给管理员
        ...
        // 下面异常中的 message 就是给用户的提示
        throw new SalException(&quot;系统出现未知异常“);
    }
}</code></code></pre>
<p>欢迎关注我的公众号</p>
<p><img src="./images/Java 基础篇之异常1.png" /></p>


</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>