<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修java 异常捕获小记' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>java 异常捕获小记</center></div><div class='banquan'>原文出处:本文由博客园博主programmerJian提供。<br/>
原文连接:https://www.cnblogs.com/programmerJian/p/11725032.html</div><br>
    <p>java 中异常捕获常用的为:</p>
<p>　　try{</p>
<p>　　　　//业务代码</p>
<p>　　}catch(Exception e){</p>
<p>　　　　//异常捕获</p>
<p>　　}finally{</p>
<p>　　　　// 不管有无异常， 最后都会执行到这里</p>
<p>　　}</p>
<p>&nbsp;</p>
<p>在方法体内如果想要把异常抛出到方法外， 在定义方法的时候 需要通过 throws 来声明所要抛出的异常类型， 在调用该方法的方法内，可以捕获该异常</p>
<p>如：&nbsp;</p>
<p>&nbsp; &nbsp;public void function(String args) throws Exception{</p>
<p>　　　　if(null == args){</p>
<p>　　　　　　throw new NullPointException("参数不能为null"); // 这里可以抛出空指针异常</p>
<p>　　　　}</p>
<p>　　　　try{</p>
<p>　　　　　//代码体</p>
<p>　　　　}catch(Exception e){</p>
<p>　　　　　　throw new Exception("抛出异常")；&nbsp; //这里可以抛出</p>
<p>　　　　}</p>
<p>}</p>
<p>在调用该方法的方法体内捕获该异常</p>
<p>public void exceptionCatchTest(){　　　</p>
<p>　　try{</p>
<p>　　　　function(null);</p>
<p>　　}catch(NullPointerException pe){</p>
<p>　　　　System.out.println(pe.getMessage); //打印function方法抛出的异常信息</p>
<p>　　　　e.printStackTrance();</p>
<p>　　}catch(Exception e){</p>
<p>　　　　System.out.println(e.getMessage); //打印function方法抛出的异常信息</p>
<p>　　　　e.printStackTrance();</p>
<p>　　}</p>
<p>}</p>
<p>&nbsp;</p>
<p>如果在方法内手动抛出异常， 而不想抛出方法外，&nbsp; 在定义方法时，不用使用throws, 而是在方法内直接用try&nbsp; catch捕获到，进行处理：&nbsp;</p>
<p>如：</p>
<p>public void function(String args) {</p>
<p>　　　</p>
<p>　　　　try{</p>
<p>　　　　　if(null == args){</p>
<p>　　　　　　throw new NullPointException("参数不能为null"); // 这里可以抛出空指针异常</p>
<p>　　　　}</p>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;//代码体</p>
<p>　　　　}catch(NullPointException pe){</p>
<p>　　　　　　 System.out.println(pe.getMessage())</p>
<p>　　　　}catch(Exception e){</p>
<p>　　　　　　&nbsp;&nbsp;System.out.println(e.getMessage())</p>
<p>　　　　}</p>
<p>}</p>
<p>&nbsp;</p>

</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>